# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rota < Formula
  desc "Plan, ship and run parallel rounds with AI coding agents"
  homepage "https://github.com/l4ci/rota"
  version "0.14.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/l4ci/rota/releases/download/v0.14.0/rota_0.14.0_darwin_amd64.tar.gz"
      sha256 "22d64a66433d0764235177775a783eb7c30a3a0ff090a15ce170cf5bef166136"

      define_method(:install) do
        bin.install "rota"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/l4ci/rota/releases/download/v0.14.0/rota_0.14.0_darwin_arm64.tar.gz"
      sha256 "51bb41fdd04349cd3e93eda014772677814cb75ec5c6aec167627b03bac228e2"

      define_method(:install) do
        bin.install "rota"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/l4ci/rota/releases/download/v0.14.0/rota_0.14.0_linux_amd64.tar.gz"
      sha256 "5e0a3182678ac3970e47aac5ac199d4af9e02d7f94d7af3cd5814efe162bf920"
      define_method(:install) do
        bin.install "rota"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/l4ci/rota/releases/download/v0.14.0/rota_0.14.0_linux_arm64.tar.gz"
      sha256 "6d0f9b2e11f330df1fcd9707805079fa4df0108ee35e89c9605c34dc5ee4a768"
      define_method(:install) do
        bin.install "rota"
      end
    end
  end

  def caveats
    <<~EOS
      Next: rota skills install
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/rota version")
  end
end
